name: shared_device_network_example
description: "Demonstration of the shared_device_network package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_background_service: ^5.1.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1

  shared_device_network:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
